### ISSUE TITLE
Co-annotation analysis - enrichment extension 

### ISSUE THREAD

**Issue by dosumis** [INCATools/pandasaurus_cxg#10]
Are any of the CL terms in the initial seed (the set of CL terms used to initialise the Pandasaurus object) also in the object column of the enrichment table?

 If so, repeat co-annotation analysis including everything that maps to this term, directly or via the enrichment table.

e.g. 

Co-annotation (in this case, everything is 1:1 => predicate cluster_matches).

```python
print(ade._anndata.obs[['author_cell_type', 'cell_type', 'cell_type_ontology_term_id']].drop_duplicates().to_csv(sep='\t'))
```

author_cell_type | cell_type | cell_type_ontology_term_id
-- | -- | --
naive B cell | naive B cell | CL:0000788
memory B cell | memory B cell | CL:0000787
gamma-delta T cell | gamma-delta T cell | CL:0000798
plasmablast | plasmablast | CL:0000980
regulatory T cell | regulatory T cell | CL:0000815
CD4-positive, alpha-beta memory T cell | CD4-positive, alpha-beta memory T cell | CL:0000897
CD8-positive, alpha-beta memory T cell | CD8-positive, alpha-beta memory T cell | CL:0000909
naive CD8+ T cell | naive thymus-derived CD8-positive, alpha-beta T cell | CL:0000900
naive CD4+ T cell | naive thymus-derived CD4-positive, alpha-beta T cell | CL:0000895
mucosal invariant T cell (MAIT) | mucosal invariant T cell | CL:0000940
TissueResMemT | memory T cell | CL:0000813
double-positive T cell (DPT) | double-positive, alpha-beta thymocyte | CL:0000809
double negative T cell (DNT) | double negative thymocyte | CL:0002489
TCRVbeta13.1pos | T cell | CL:0000084

enrichment table:

```python
print(ade.minimal_slim_enrichment(['simple_term_enrichment']).to_csv(sep='\t'))
```

  | s | s_label | p | o | o_label
-- | -- | -- | -- | -- | --
0 | CL:0000895 | naive thymus-derived CD4-positive, alpha-beta T cell | rdfs:subClassOf | CL:0000084 | T cell
1 | CL:0000897 | CD4-positive, alpha-beta memory T cell | rdfs:subClassOf | CL:0000084 | T cell
2 | CL:0000900 | naive thymus-derived CD8-positive, alpha-beta T cell | rdfs:subClassOf | CL:0000084 | T cell
3 | CL:0000909 | CD8-positive, alpha-beta memory T cell | rdfs:subClassOf | CL:0000084 | T cell
4 | CL:0000940 | mucosal invariant T cell | rdfs:subClassOf | CL:0000084 | T cell
5 | CL:0002489 | double negative thymocyte | rdfs:subClassOf | CL:0000084 | T cell
6 | CL:0000897 | CD4-positive, alpha-beta memory T cell | rdfs:subClassOf | CL:0000813 | memory T cell
7 | CL:0000909 | CD8-positive, alpha-beta memory T cell | rdfs:subClassOf | CL:0000813 | memory T cell
8 | CL:0000798 | gamma-delta T cell | rdfs:subClassOf | CL:0000084 | T cell
9 | CL:0000809 | double-positive, alpha-beta thymocyte | rdfs:subClassOf | CL:0000084 | T cell
10 | CL:0000813 | memory T cell | rdfs:subClassOf | CL:0000084 | T cell
11 | CL:0000815 | regulatory T cell | rdfs:subClassOf | CL:0000084 | T cell

T-Cell; CL:0000084  is in original seed (from obs.cell_type...) and in the object column of the enrichment table.  

Co-occurence analysis without enrichment => TCRVbeta13.1pos cluster_matches T cell (CL:0000084)

Co-occurence analysis with enrichment =>

TCRVbeta13.1pos subClusterOf  T cell( CL:0000084)
mucosal invariant T cell (MAIT)  subClusterOf  T cell( CL:0000084)
...

(Note: working through like this makes it clear that we need to start making the distinction between ontology terms (where subClassOf is appropriate) and cell sets defined by tagging with ontology terms (cell sets are related by subClusterOf).  This will be important for the model, but needs to be handled carefully for user facing assertions.  For now, I think we need to gloss this distinction.)

**Comment by dosumis** [comment]
CC @hkir-dev

**Comment by ubyndr** [comment]
> Co-occurence analysis **without** enrichment =>
> 
> TCRVbeta13.1pos **subClusterOf** T cell (CL:0000084) 
> regulatory T cell (CL:0000815) subClusterOf T cell( CL:0000084)

@dosumis did you mean **with** or **cluster_matches**? 

> Are any of the CL terms in the initial seed also in the object column of the enrichment table?

Isn't this the default for the simple enrichment? Am I missing something here?

First, I thought you wanted apply some sort of transitive relationship between author cell types with the other cell types, i.e. `regulatory T cell rdfs:subClassOf TCRVbeta13.1pos`. It is not clear what kind of output do you wish to see with this report.
