### ISSUE TITLE
Generate graphs of cell sets + cell ontology (enrichment) classes

### ISSUE THREAD

**Issue by dosumis** [INCATools/pandasaurus_cxg#13]
One of the main aims of Pandasaurus_CxG is to use it to build a graph/tree showing the implicit hierarchy of cell (type) annotations based on co-annotation, relating this back to the ontology subClass graph.

To do this we should:

1.  Unify sets of annotations on the same cell_set (all labels linked by cluster_matches).
2. Generate a graph using subClusterOf between cell sets. 
3. Relate cell sets to ontology terms using some standard relation (consists of?)

We should then support display of a simple graph of cell sets (MVP) & one extended using ontology (subClassOf) hierarchy to terms in the enrichment.  To make this manageable for large datasets it should be possible to choose to generate a graph visualisation from some set of cell sets.

Note we still need to keep track of labelsets (the set of terms under one obs).

REPRESENTATION: represent in RDF as individuals. We should follow the schema in [Tan et al., 2022](https://www.nature.com/articles/s41597-022-01886-2) and generate using SPARQL UPDATE.
TBD: How to translate OBS key names into APs.

Outputs: It should be possible to save the resulting RDF to disk.  It can be used as input to OBASK.

VISUALIZATION: Use OAKLIB. It works nicely with OWL.  

Difficulties: 

* Visualization requires a choice of which keys to use to label nodes, but we can't know the obs names *a priori*.  
     * SOLUTION:  Users get choice of preferred keys for visualization on graph visualization generation method. 
     * [x] #30

Breakdown:
 - [x] #26
 - [x] #27

**Comment by dosumis** [comment]
TODO: Decide on underlying representation . Could be RDF, then convert to NetworkX for visualization.

**Comment by dosumis** [comment]
@ubyndr  - please review. I think this is ready for implementation.  High priority.

**Comment by ubyndr** [comment]
This has been resolved with #26, #27 and #30
