### ISSUE TITLE
Supported workflows

### ISSUE THREAD

**Issue by dosumis** [INCATools/pandasaurus_cxg#31]
Wrapper object
   * User initialises with a CxG  anndata file.
   * this wraps analyzer and enricher objects

Analyzer object
   * User initialises chooses free text cell type fields --> analysis  (#14) 
 
Enricher object 
   * Runs enrichment method. => enrichment tables + graphs (both stored on object). graphs are rdf, transitively reduced.  Stored in memory. 

Graph generation (on wrapper object)
   *  User specifies priority list of obs to use for label --> generates RDF graph of co-annotation (transitively reduced) (#30) 
   *  Generate enriched graph (combining with co-annotation graph)
   * Outputs: 
        * Visualize graphs with networkX
        * Save as rdf
        * Return networkX object.
   
Tasks:
- [x] #32

**Comment by ubyndr** [comment]
This has been resolved with #32
