### ISSUE TITLE
Contextual enrichment should restrict to cells

### ISSUE THREAD

**Issue by dosumis** [INCATools/pandasaurus_cxg#35]
Inspecting the RDF graph generated by working on the kidney example file, there are Uberon terms in, that have CL IDs.
![image](https://github.com/INCATools/pandasaurus_cxg/assets/112839/e8f01673-766f-460a-ad1f-0625a810252e)
![image](https://github.com/INCATools/pandasaurus_cxg/assets/112839/1752713b-0c20-4b4a-a61f-c91912040bde)
![image](https://github.com/INCATools/pandasaurus_cxg/assets/112839/35431b1e-94ac-4177-8a5d-3bf3a0f8b312)

This suggests 2 bugs that need fixing:

- [ ] contextual enrichment in pandasaurus_cxg should by restricted to subClassOf CL:cell. 
   This does not harm for graph/enrichment generation, so is not urgent to fix.
- [ ] #36
    This is quite serious as we don't want files with incorrect IDs getting out into the wild.  In general we should always avoid rewriting IRIs, rather than taking them as-is from source.

**Comment by ubyndr** [comment]
The first item is related with `get_contextual_enrichment_query` method in the pandasaurus, and I will make a PR in there.
The second item will be automatically fix when the pandasaurus is updated. I only add the terms from enrichment tables to enrich the generated graph with terms. When I restrict CL terms, this part will work as intended;
```python
        # add cell_type nodes and consists_of relations
        cl_namespace = Namespace("http://purl.obolibrary.org/obo/CL_")
        for curie, label in self.cell_type_dict.items():
            resource = cl_namespace[curie.split(":")[-1]]
            self.graph.add((resource, RDFS.label, Literal(label)))
            self.graph.add((resource, RDF.type, OWL.Class))
            for s, _, _ in self.graph.triples((None, self.ns["cell_type"], Literal(label))):
                # Add the triples to represent the restriction
                class_expression_bnode = BNode()
                self.graph.add((class_expression_bnode, RDF.type, OWL.Restriction))
                self.graph.add((class_expression_bnode, OWL.onProperty, self.ns["consist_of"]))
                self.graph.add((class_expression_bnode, OWL.someValuesFrom, resource))
                # Add the restriction
                self.graph.add((s, RDF.type, class_expression_bnode))
```
