### ISSUE TITLE
GraphGeneration.visualize_rdf_graph needs pydoc

### ISSUE THREAD

**Issue by dosumis** [INCATools/pandasaurus_cxg#37]
In general we need better documentation on how to run this:

How is the node list used to generate graphs?
What is the predicate argument used for?

This should be in PyDoc, but we also need examples in notebook of how we expect users to discover nodes.

**Comment by ubyndr** [comment]
Added docstring in https://github.com/INCATools/pandasaurus_cxg/pull/34/commits/57e871aef2087595d78427b9b4e1945f1db66797

**Comment by ubyndr** [comment]
This has been resolved with https://github.com/INCATools/pandasaurus_cxg/pull/34
