### ISSUE TITLE
Set IRIs 

### ISSUE THREAD

**Issue by dosumis** [INCATools/pandasaurus_cxg#39]
consist_of --> iri": "http://purl.obolibrary.org/obo/RO_0002473",  "label": "composed_primarily_of"
subcluster_of -> iri: "http://purl.obolibrary.org/obo/RO_0015003", "label": "subcluster of"
cluster --> iri: http://purl.obolibrary.org/obo/PCL_0010001", "label": "cell cluster"  # This one might change

**Comment by dosumis** [comment]
Would like to fix before release.

**Comment by ubyndr** [comment]
This has been resolved with https://github.com/INCATools/pandasaurus_cxg/pull/34
