### ISSUE TITLE
Add new enrichment method

### ISSUE THREAD

**Issue by dosumis** [INCATools/pandasaurus_cxg#46]
add another enrichment method to the existing set. 

User specifies number of hops

name: ancestor_enrichment (?)
Args: number of hops

subject - terms in seed
object - terms in seed + terms 1-n hops from terms in subject.

**Comment by ubyndr** [comment]
This should go to pandasaurus rather than pandasaurus_cxg, shouldn't it?

**Comment by ubyndr** [comment]
PR is up at https://github.com/INCATools/PandaSaurus/pull/37
